apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet-app
  template:
    metadata:
      labels:
        app: greet-app
    spec:
      containers:
      - name: greet-app
        image: minaeshak/greet:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greet-app
spec:
  selector:
    app: greet-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greet-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: greeting-api.acme.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greet-app
            port:
              number: 8080
  tls:
  - hosts:
    - greeting-api.acme.co
    secretName: greeting-api-tls
