apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet-app
  template:
    metadata:
      labels:
        app: greet-app
    spec:
      containers:
      - name: greet-app
        image: mina-eshak/greet-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greet-app
spec:
  selector:
    app: greet-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer